name: luno_budget_money
description: A new Flutter project.
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  form_field_validator: ^1.1.0
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  fluttertoast: ^8.2.2
  google_sign_in: ^6.1.4
  dio: ^5.3.0
  image_picker: ^1.0.1
  video_player: ^2.7.0
  json_annotation: ^4.8.1
  intl: ^0.18.1
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.2.0
  cloud_firestore: ^4.8.4
  flutter_date_range_picker: ^0.0.14
  cached_network_image: ^3.2.3

dev_dependencies:
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/


