// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBH1vC9mQ3oFEqFanqDBk6Q2ThJ8BGyZ-o',
    appId: '1:221429173207:android:a039c02bf7134b3d38d992',
    messagingSenderId: '221429173207',
    projectId: 'luno-budget-money',
    storageBucket: 'luno-budget-money.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0K2g-gCXxYCMMb58kQeHkouGvQZlXIKc',
    appId: '1:221429173207:ios:06dac70a8d3267e838d992',
    messagingSenderId: '221429173207',
    projectId: 'luno-budget-money',
    storageBucket: 'luno-budget-money.appspot.com',
    androidClientId: '221429173207-kt0pacjrcsaa79d1dfol32sbvg0l6f09.apps.googleusercontent.com',
    iosClientId: '221429173207-f5fh0sstqp41bgnplvcm093hrjngpn0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.lunoBudgetMoney',
  );
}
